version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: inflearn-project-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prismapass
      POSTGRES_DB: inflearn_project
    volumes:
      - inflearn_project_db:/var/lib/postgresql

volumes:
  inflearn_project_db:
